// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAibbwXhbPTg7wCesIHf5KFB29mEenw3lA',
    appId: '1:981862459735:web:97e21cb61ee3a69b937612',
    messagingSenderId: '981862459735',
    projectId: 'shilposathi-16aea',
    authDomain: 'shilposathi-16aea.firebaseapp.com',
    storageBucket: 'shilposathi-16aea.firebasestorage.app',
    measurementId: 'G-07SSWV6FHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg-4se70U5b8jirLw7c8wITd84_OkGSBk',
    appId: '1:981862459735:android:568c99cc3bd3d733937612',
    messagingSenderId: '981862459735',
    projectId: 'shilposathi-16aea',
    storageBucket: 'shilposathi-16aea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjzDq2Z05Cu9qtCDddJWJozUBcym2DQlU',
    appId: '1:981862459735:ios:94bca02031faefc2937612',
    messagingSenderId: '981862459735',
    projectId: 'shilposathi-16aea',
    storageBucket: 'shilposathi-16aea.firebasestorage.app',
    iosBundleId: 'com.example.shilpoSathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAibbwXhbPTg7wCesIHf5KFB29mEenw3lA',
    appId: '1:981862459735:web:c2016f40d06fde39937612',
    messagingSenderId: '981862459735',
    projectId: 'shilposathi-16aea',
    authDomain: 'shilposathi-16aea.firebaseapp.com',
    storageBucket: 'shilposathi-16aea.firebasestorage.app',
    measurementId: 'G-1WY4XYEC9V',
  );
}
